//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConcept3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ficha
    {
        public string Nome { get; set; }
        public int ID { get; set; }
        public System.DateTime Nascimento { get; set; }
        public string Gênero { get; set; }
        public string Local { get; set; }
    }
}
